In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('Employee.csv')
df=pd.DataFrame(data)
df

      Education  JoiningYear  ... ExperienceInCurrentDomain  LeaveOrNot
0     Bachelors         2017  ...                         0           0
1     Bachelors         2013  ...                         3           1
2     Bachelors         2014  ...                         2           0
3       Masters         2016  ...                         5           1
4       Masters         2017  ...                         2           1
...         ...          ...  ...                       ...         ...
4648  Bachelors         2013  ...                         4           0
4649    Masters         2013  ...                         2           1
4650    Masters         2018  ...                         5           1
4651  Bachelors         2012  ...                         2           0
4652  Bachelors         2015  ...                         4           0

[4653 rows x 9 columns]

In [7]:
standardScaler=StandardScaler()
standardScaled=standardScaler.fit_transform(df[['JoiningYear','Age']])

pd.DataFrame(standardScaled,columns=['JoiningYear','Age'])

      JoiningYear       Age
0        1.039638  0.954645
1       -1.107233 -0.288732
2       -0.570515  1.783563
3        0.502921 -0.495961
4        1.039638 -1.117650
...           ...       ...
4648    -1.107233 -0.703191
4649    -1.107233  1.576334
4650     1.576356 -0.495961
4651    -1.643951  0.125727
4652    -0.033797  0.747416

[4653 rows x 2 columns]

In [8]:
minMaxScaler=MinMaxScaler()
minMaxScaled=minMaxScaler.fit_transform(df[['JoiningYear','Age']])

pd.DataFrame(minMaxScaled,columns=['JoiningYear','Age'])

      JoiningYear       Age
0        0.833333  0.631579
1        0.166667  0.315789
2        0.333333  0.842105
3        0.666667  0.263158
4        0.833333  0.105263
...           ...       ...
4648     0.166667  0.210526
4649     0.166667  0.789474
4650     1.000000  0.263158
4651     0.000000  0.421053
4652     0.500000  0.578947

[4653 rows x 2 columns]

In [9]:
X=df[['JoiningYear']]
y=df[['Age']]

XTrain,XTest,yTrain,yTest=train_test_split(X,y,test_size=0.5,random_state=42)

print("Trainin data and Testind data of X 'JoiningYear'")
print(XTrain,XTest)
print("Trainin data and Testind data of y 'Age'")
print(yTrain,yTest)

Trainin data and Testind data of X 'JoiningYear'
      JoiningYear
4238         2014
2130         2012
982          2015
456          2015
3083         2018
...           ...
4426         2014
466          2013
3092         2016
3772         2015
860          2015

[2326 rows x 1 columns]       JoiningYear
297          2016
2705         2013
501          2017
1272         2015
3956         2012
...           ...
3919         2015
4627         2012
4371         2016
1352         2017
3003         2017

[2327 rows x 1 columns]
Trainin data and Testind data of y 'Age'
      Age
4238   31
2130   26
982    25
456    25
3083   41
...   ...
4426   32
466    26
3092   39
3772   41
860    27

[2326 rows x 1 columns]       Age
297    24
2705   26
501    25
1272   28
3956   33
...   ...
3919   31
4627   30
4371   27
1352   27
3003   32

[2327 rows x 1 columns]